//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HeThongDiemDanh.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class diemdanh
    {
        public int id { get; set; }
        public Nullable<bool> cot1 { get; set; }
        public Nullable<bool> cot2 { get; set; }
        public Nullable<bool> cot3 { get; set; }
    }
}
