//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HeThongDiemDanh.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DIEMDANHSV
    {
        public int IDDDSV { get; set; }
        public System.DateTime THOIGIANDDSV { get; set; }
        public string GHICHU { get; set; }
        public int IDLICHHOC { get; set; }
        public int IDLOPMH { get; set; }
        public int IDNGUOIDUNG { get; set; }
    
        public virtual LICHHOC LICHHOC { get; set; }
    }
}
