//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HeThongDiemDanh.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LICHHOC
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LICHHOC()
        {
            this.DIEMDANHSVs = new HashSet<DIEMDANHSV>();
        }
    
        public int IDLICHHOC { get; set; }
        public System.DateTime THOIGIANDIEMDANH { get; set; }
        public int TUANHOC { get; set; }
        public string MAQR { get; set; }
        public int IDLOPMH { get; set; }
        public int IDNGUOIDUNG { get; set; }
    
        public virtual DANHSACHLOP DANHSACHLOP { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DIEMDANHSV> DIEMDANHSVs { get; set; }
    }
}
