//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HeThongDiemDanh.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LOPMONHOC
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LOPMONHOC()
        {
            this.DANHSACHLOPs = new HashSet<DANHSACHLOP>();
        }
    
        public int IDLOPMH { get; set; }
        public string MALOPMH { get; set; }
        public string TENLOPMH { get; set; }
        public int NHOMMONHOC { get; set; }
        public bool TOTHUCHANH { get; set; }
        public string THU { get; set; }
        public Nullable<int> SOTIET { get; set; }
        public Nullable<int> TIETBATDAU { get; set; }
        public System.DateTime NGAYBATDAU { get; set; }
        public System.DateTime NGAYKETTHUC { get; set; }
        public string PHONGHOC { get; set; }
        public int IDMONHOC { get; set; }
        public int IDHOCKY { get; set; }
        public int IDGIANGVIEN { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DANHSACHLOP> DANHSACHLOPs { get; set; }
        public virtual HOCKY HOCKY { get; set; }
        public virtual NGUOIDUNG NGUOIDUNG { get; set; }
        public virtual MONHOC MONHOC { get; set; }
    }
}
