//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HeThongDiemDanh.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NGUOIDUNG
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public NGUOIDUNG()
        {
            this.CHITIETQUYENNGUOIDUNGs = new HashSet<CHITIETQUYENNGUOIDUNG>();
            this.DANHSACHLOPs = new HashSet<DANHSACHLOP>();
            this.LOPMONHOCs = new HashSet<LOPMONHOC>();
        }
    
        public int IDNGUOIDUNG { get; set; }
        public int IDPHANQUYEN { get; set; }
        public string MASONGUOIDUNG { get; set; }
        public string TENNGUOIDUNG { get; set; }
        public Nullable<System.DateTime> NGAYSINH { get; set; }
        public string EMAIL { get; set; }
        public string SODIENTHOAI { get; set; }
        public string DIACHI { get; set; }
        public Nullable<int> IDLOPSINHVIEN { get; set; }
        public string TENDANGNHAP { get; set; }
        public string MATKHAU { get; set; }
        public string ResetPasswordCode { get; set; }
        public Nullable<bool> IsEmailVerified { get; set; }
        public Nullable<System.Guid> ActivationCode { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CHITIETQUYENNGUOIDUNG> CHITIETQUYENNGUOIDUNGs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DANHSACHLOP> DANHSACHLOPs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LOPMONHOC> LOPMONHOCs { get; set; }
        public virtual LOPSINHVIEN LOPSINHVIEN { get; set; }
        public virtual PHANQUYEN PHANQUYEN { get; set; }
    }
}
