//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HeThongDiemDanh.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class QUYENNGUOIDUNG
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public QUYENNGUOIDUNG()
        {
            this.CHITIETQUYENNGUOIDUNGs = new HashSet<CHITIETQUYENNGUOIDUNG>();
        }
    
        public int IDQUYENNGUOIDUNG { get; set; }
        public string NOIDUNGQUYEN { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CHITIETQUYENNGUOIDUNG> CHITIETQUYENNGUOIDUNGs { get; set; }
    }
}
